[general]
temp-day=6500
temp-night=3500
fade=1
location-provider=manual

[manual]
; Для работы фиксированного времени нужны любые фиктивные координаты
lat=54.7
lon=55.9

; Настройка фиксированного времени (вместо солнца)
[fixed]
dawn-time=07:00
dusk-time=20:00
