# --- Настройка фона и размытия ---
background {
    monitor =
    # Делает скриншот экрана для размытия
    path = screenshot
    blur_passes = 3 # Больше проходов = сильнее размытие
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vignette = true
    vignette_thickness = 0.5
}

# --- Виджет часов ---
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%H:%M")"
    color = rgba(235, 219, 178, 1.0)
    font_size = 80
    font_family = JetBrains Mono ExtraBold 
    position = 0, 150
    halign = center
    valign = center
}

# --- Виджет даты ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(235, 219, 178, 0.7)
    font_size = 20
    font_family = JetBrains Mono Medium
    position = 0, 70
    halign = center
    valign = center
}

# --- Прямоугольное поле ввода (Input Field) ---
input-field {
    monitor =
    size = 340, 50
    outline_thickness = 3
    dots_size = 0.2 # Размер точек скрытия пароля (0.2 - 0.8)
    dots_spacing = 0.15 # Расстояние между точками
    dots_center = true
    
    # Цвета поля
    outer_color = rgba(102, 92, 84, 1.0) # Граница
    inner_color = rgba(40, 40, 40, 0.8)  # Фон инпута
    font_color = rgba(235, 219, 178, 1.0) # Цвет текста / точек
    
    fade_on_empty = false # Не скрывать инпут, если он пустой
    placeholder_text = <i>Введите пароль...</i> # Текст-подсказка
    hide_input = false
    
    # Позиционирование (чуть ниже центра экрана)
    position = 0, -50
    halign = center
    valign = center
}

# --- Виджет текущей раскладки клавиатуры ---
label {
    monitor =
    text = $LAYOUT
    color = rgba(235, 219, 178, 0.6) # Слегка прозрачный цвет
    font_size = 14
    font_family = JetBrains Mono

    onclick = swaymsg input "type:keyboard" xkb_switch_layout next

    # Позиционирование: прямо над полем ввода пароля
    position = 0, 5 
    halign = center
    valign = center
}

# --- Виджет для показа времени ---
label {
  monitor =
  text = cmd[update:60000] ~/.config/hypr/scripts/battery.sh
  font_size = 20
  font_family = JetBrains Mono # Замените на ваш шрифт
  color = rgba(255, 255, 255, 1.0)

  halign = right
  valign = bottom

  position = -50, 50
}
